-- Supabase Schema for Sportsense (Custom Auth, No Supabase Auth)
-- Исправленная версия: RLS отключён для разработки, correct identity, proper constraints

-- Enable UUID extension if needed for other tables
create extension if not exists "uuid-ossp";

-- ======================= USERS TABLE =======================
-- Custom users table with password_hash (no Supabase Auth)
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text,
  email text not null unique,
  password_hash text not null,
  created_at timestamptz not null default now()
);

-- В development отключаем RLS для простоты (в production нужно настроить правильно)
alter table public.users disable row level security;

-- Если RLS включен, создаемpermiscive policies для разработки
do $$
begin
  if exists (
    select 1 from pg_tables 
    where schemaname = 'public' 
    and tablename = 'users' 
    and rowsecurity = true
  ) then
    -- Drop existing policies if any
    drop policy if exists "Users can view own profile" on public.users;
    drop policy if exists "Users can insert own profile" on public.users;
    drop policy if exists "Users can update own profile" on public.users;
    drop policy if exists "Users can delete own profile" on public.users;

    -- Create permissive policies for development (allow all for authenticated)
    create policy "Allow all for authenticated users" on public.users
      for all using (true) with check (true);
  end if;
end $$;

-- ======================= CHATS TABLE =======================
create table if not exists public.chats (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  title text not null,
  created_at timestamptz not null default now()
);

alter table public.chats disable row level security;

do $$
begin
  if exists (
    select 1 from pg_tables 
    where schemaname = 'public' 
    and tablename = 'chats' 
    and rowsecurity = true
  ) then
    drop policy if exists "Users can view own chats" on public.chats;
    drop policy if exists "Users can insert own chats" on public.chats;
    drop policy if exists "Users can update own chats" on public.chats;
    drop policy if exists "Users can delete own chats" on public.chats;

    create policy "Allow all for authenticated users" on public.chats
      for all using (true) with check (true);
  end if;
end $$;

-- ======================= MESSAGES TABLE =======================
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  chat_id bigint not null references public.chats(id) on delete cascade,
  text text not null,
  is_user integer not null check (is_user in (0, 1)),
  timestamp timestamptz not null default now()
);

alter table public.messages disable row level security;

do $$
begin
  if exists (
    select 1 from pg_tables 
    where schemaname = 'public' 
    and tablename = 'messages' 
    and rowsecurity = true
  ) then
    drop policy if exists "Users can view messages of own chats" on public.messages;
    drop policy if exists "Users can insert messages to own chats" on public.messages;
    drop policy if exists "Users can delete messages of own chats" on public.messages;

    create policy "Allow all for authenticated users" on public.messages
      for all using (true) with check (true);
  end if;
end $$;

-- ======================= SAVED_ITEMS TABLE =======================
create table if not exists public.saved_items (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  title text not null,
  subtitle text not null,
  type text not null,
  metadata text,
  created_at timestamptz not null default now()
);

alter table public.saved_items disable row level security;

do $$
begin
  if exists (
    select 1 from pg_tables 
    where schemaname = 'public' 
    and tablename = 'saved_items' 
    and rowsecurity = true
  ) then
    drop policy if exists "Users can view own saved items" on public.saved_items;
    drop policy if exists "Users can insert own saved items" on public.saved_items;
    drop policy if exists "Users can delete own saved items" on public.saved_items;

    create policy "Allow all for authenticated users" on public.saved_items
      for all using (true) with check (true);
  end if;
end $$;

-- ======================= INDEXES =======================
create index if not exists idx_users_email on public.users(email);
create index if not exists idx_chats_user_id on public.chats(user_id);
create index if not exists idx_messages_chat_id on public.messages(chat_id);
create index if not exists idx_saved_items_user_id on public.saved_items(user_id);

-- ======================= FIX SEQUENCE FOR USERS.ID =======================
-- Синхронизируем sequence с максимальным id в таблице (если есть записи)
select setval('public.users_id_seq', coalesce(max(id), 0) + 1, false) 
from public.users;

-- ======================= GRANT PERMISSIONS =======================
grant usage on schema public to authenticated;
grant all on public.users to authenticated;
grant all on public.chats to authenticated;
grant all on public.messages to authenticated;
grant all on public.saved_items to authenticated;

-- Для anon (если нужно)
grant usage on schema public to anon;
grant select, insert, update, delete on public.users to anon;
grant select, insert, update, delete on public.chats to anon;
grant select, insert, update, delete on public.messages to anon;
grant select, insert, update, delete on public.saved_items to anon;
