-- Supabase Schema for Sportsense
-- Run these SQL commands in the Supabase SQL Editor (https://app.supabase.com/project/_/sql)

-- Enable UUID extension if not already enabled
create extension if not exists "uuid-ossp";

-- ======================= USERS TABLE =======================
-- Links Supabase Auth users to application data
create table public.users (
  id bigint generated by default as identity primary key,
  auth_uid uuid references auth.users(id) on delete cascade unique,
  name text not null,
  email text not null,
  created_at timestamptz not null default now()
);

-- Enable Row Level Security
alter table public.users enable row level security;

-- RLS Policies for users
create policy "Users can view own profile"
  on public.users for select
  using (auth.uid() = auth_uid);

create policy "Users can insert own profile"
  on public.users for insert
  with check (auth.uid() = auth_uid);

create policy "Users can update own profile"
  on public.users for update
  using (auth.uid() = auth_uid);

-- ======================= CHATS TABLE =======================
create table public.chats (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  title text not null,
  created_at timestamptz not null default now()
);

alter table public.chats enable row level security;

create policy "Users can view own chats"
  on public.chats for select
  using (
    exists (
      select 1 from public.users
      where users.id = chats.user_id
      and users.auth_uid = auth.uid()
    )
  );

create policy "Users can insert own chats"
  on public.chats for insert
  with check (
    exists (
      select 1 from public.users
      where users.id = chats.user_id
      and users.auth_uid = auth.uid()
    )
  );

create policy "Users can update own chats"
  on public.chats for update
  using (
    exists (
      select 1 from public.users
      where users.id = chats.user_id
      and users.auth_uid = auth.uid()
    )
  );

create policy "Users can delete own chats"
  on public.chats for delete
  using (
    exists (
      select 1 from public.users
      where users.id = chats.user_id
      and users.auth_uid = auth.uid()
    )
  );

-- ======================= MESSAGES TABLE =======================
create table public.messages (
  id bigint generated by default as identity primary key,
  chat_id bigint not null references public.chats(id) on delete cascade,
  text text not null,
  is_user integer not null check (is_user in (0, 1)),
  timestamp timestamptz not null default now()
);

alter table public.messages enable row level security;

create policy "Users can view messages of own chats"
  on public.messages for select
  using (
    exists (
      select 1 from public.chats
      join public.users on users.id = chats.user_id
      where chats.id = messages.chat_id
      and users.auth_uid = auth.uid()
    )
  );

create policy "Users can insert messages to own chats"
  on public.messages for insert
  with check (
    exists (
      select 1 from public.chats
      join public.users on users.id = chats.user_id
      where chats.id = messages.chat_id
      and users.auth_uid = auth.uid()
    )
  );

create policy "Users can delete messages of own chats"
  on public.messages for delete
  using (
    exists (
      select 1 from public.chats
      join public.users on users.id = chats.user_id
      where chats.id = messages.chat_id
      and users.auth_uid = auth.uid()
    )
  );

-- ======================= SAVED_ITEMS TABLE =======================
create table public.saved_items (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  title text not null,
  subtitle text not null,
  type text not null,
  metadata text,
  created_at timestamptz not null default now()
);

alter table public.saved_items enable row level security;

create policy "Users can view own saved items"
  on public.saved_items for select
  using (
    exists (
      select 1 from public.users
      where users.id = saved_items.user_id
      and users.auth_uid = auth.uid()
    )
  );

create policy "Users can insert own saved items"
  on public.saved_items for insert
  with check (
    exists (
      select 1 from public.users
      where users.id = saved_items.user_id
      and users.auth_uid = auth.uid()
    )
  );

create policy "Users can delete own saved items"
  on public.saved_items for delete
  using (
    exists (
      select 1 from public.users
      where users.id = saved_items.user_id
      and users.auth_uid = auth.uid()
    )
  );

-- ======================= INDEXES FOR PERFORMANCE =======================
create index idx_users_auth_uid on public.users(auth_uid);
create index idx_chats_user_id on public.chats(user_id);
create index idx_messages_chat_id on public.messages(chat_id);
create index idx_saved_items_user_id on public.saved_items(user_id);

-- ======================= HELPER FUNCTION TO CREATE PROFILE AFTER SIGNUP =======================
-- This function automatically creates a user profile when a new auth user signs up
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.users (auth_uid, name, email, created_at)
  values (new.id, new.raw_user_meta_data->>'name', new.email, now());
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to call the function on auth user creation
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- ======================= GRANT PERMISSIONS =======================
-- Allow authenticated users to use the functions
grant usage on schema public to authenticated;
grant all on public.users to authenticated;
grant all on public.chats to authenticated;
grant all on public.messages to authenticated;
grant all on public.saved_items to authenticated;
