-- Supabase Schema for Sportsense (Custom Auth, No Supabase Auth)
-- ИСПРАВЛЕНО: RLS отключён для development, правильная identity последовательность

-- Enable UUID extension if needed for other tables
create extension if not exists "uuid-ossp";

-- ======================= USERS TABLE =======================
-- Custom users table with password_hash (no Supabase Auth)
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text,
  email text not null unique,
  password_hash text not null,
  created_at timestamptz not null default now()
);

-- В development отключаем RLS для простоты (в production включить и настроить правильно)
alter table public.users disable row level security;

-- ======================= CHATS TABLE =======================
create table if not exists public.chats (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  title text not null,
  created_at timestamptz not null default now()
);

alter table public.chats disable row level security;

-- ======================= MESSAGES TABLE =======================
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  chat_id bigint not null references public.chats(id) on delete cascade,
  text text not null,
  is_user integer not null check (is_user in (0, 1)),
  timestamp timestamptz not null default now()
);

alter table public.messages disable row level security;

-- ======================= SAVED_ITEMS TABLE =======================
create table if not exists public.saved_items (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  title text not null,
  subtitle text not null,
  type text not null,
  metadata text,
  created_at timestamptz not null default now()
);

alter table public.saved_items disable row level security;

-- ======================= INDEXES =======================
create index if not exists idx_users_email on public.users(email);
create index if not exists idx_chats_user_id on public.chats(user_id);
create index if not exists idx_messages_chat_id on public.messages(chat_id);
create index if not exists idx_saved_items_user_id on public.saved_items(user_id);

-- ======================= FIX SEQUENCE (IMPORTANT!) =======================
-- Синхронизируем sequence с максимальным id в таблице, чтобы избежать дубликатов
-- Выполняется при каждой миграции, безопасно для существующих данных
select setval('public.users_id_seq', coalesce(max(id), 0) + 1, false) 
from public.users;

select setval('public.chats_id_seq', coalesce(max(id), 0) + 1, false) 
from public.chats;

select setval('public.messages_id_seq', coalesce(max(id), 0) + 1, false) 
from public.messages;

select setval('public.saved_items_id_seq', coalesce(max(id), 0) + 1, false) 
from public.saved_items;

-- ======================= GRANT PERMISSIONS =======================
grant usage on schema public to authenticated;
grant all on public.users to authenticated;
grant all on public.chats to authenticated;
grant all on public.messages to authenticated;
grant all on public.saved_items to authenticated;

-- Для anon (если нужно разрешить доступ без аутентификации)
grant usage on schema public to anon;
grant select, insert, update, delete on public.users to anon;
grant select, insert, update, delete on public.chats to anon;
grant select, insert, update, delete on public.messages to anon;
grant select, insert, update, delete on public.saved_items to anon;

-- =======================
-- NOTE: You need to set the app.current_user_id session variable
-- after login in your Flutter app:
--
// Example (after successful login):
// await supabase.rpc('set_user_id', {'user_id': userId});
// Or use JWT claims if you switch to real auth later.
--
-- For now, the app will use direct queries with WHERE user_id = ?
-- and not rely on RLS session variables. RLS policies above use the
-- session variable approach for security, but the Flutter queries
-- explicitly filter by user_id anyway (defense-in-depth).
-- The app uses .eq('user_id', userId) on all user-scoped queries.